create table if not exists public.folders(id bigint generated by default as identity primary key,name text unique not null,created_at timestamptz default now());
create table if not exists public.works(id bigint generated by default as identity primary key,title text not null,folder text not null,image text not null,storage_path text not null,created_at timestamptz default now());
alter table public.folders enable row level security; alter table public.works enable row level security;
create policy "public read folders" on public.folders for select using(true);
create policy "public read works" on public.works for select using(true);
create policy "auth insert folders" on public.folders for insert to authenticated with check(true);
create policy "auth update folders" on public.folders for update to authenticated using(true);
create policy "auth insert works" on public.works for insert to authenticated with check(true);
create policy "auth delete works" on public.works for delete to authenticated using(true);
insert into public.folders(name) values('Gaming Thumbnails'),('Esports'),('Posters'),('Logos'),('Overlays') on conflict(name) do nothing;
-- Create a PUBLIC Storage bucket named portfolio, then add:
create policy "public portfolio read" on storage.objects for select using(bucket_id='portfolio');
create policy "auth portfolio upload" on storage.objects for insert to authenticated with check(bucket_id='portfolio');
create policy "auth portfolio delete" on storage.objects for delete to authenticated using(bucket_id='portfolio');